### ISSUE TITLE
Fehler beim lokalen bauen 

### ISSUE THREAD

**Issue by baehll** [baehll/neosyn#126]
hey @cknott 

wenn ich ein `npm run build` durchführe, bekomme ich folgende Fehlermeldung. Weißt du, was das damit auf sich hat?

```
[vite]: Rollup failed to resolve import "logo" from "C:/dev/neosyn/client/src/components/inbox/Message.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "logo" from "C:/dev/neosyn/client/src/components/inbox/Message.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///C:/dev/neosyn/client/node_modules/vite/dist/node/chunks/dep-52909643.js:48216:27)
    at onRollupWarning (file:///C:/dev/neosyn/client/node_modules/vite/dist/node/chunks/dep-52909643.js:48248:9)
    at onwarn (file:///C:/dev/neosyn/client/node_modules/vite/dist/node/chunks/dep-52909643.js:47976:13)
    at file:///C:/dev/neosyn/client/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file:///C:/dev/neosyn/client/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)        
    at ModuleLoader.handleInvalidResolvedId (file:///C:/dev/neosyn/client/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file:///C:/dev/neosyn/client/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
```

**Comment by baehll** [comment]
jo der build funktioniert
